class CranePhisycal:
    def __init__(self):
        self.arduino = ...

    def start(self):
        ...

    def move_arm(self, velocity: int):
        ...

    def move_crab(self, velocity: int):
        ...
